Case Study on Preprocessing / 
 - Dataset Overview
        Load the dataset House_Pricing.csv
        Display basic information about the dataset using .info() and .describe() to understand the features, data types, and any initial insights into missing values.
 - Duplicate Removal
        Rows: Check for duplicate rows in the dataset, if any, and remove them.
        Columns: Identify and drop duplicate columns, if any, based on their values.
 - Handling Missing Values
        Identify missing values in each column.
        Handle missing values:
            For numerical columns, use imputation techniques like mean/median imputation.
            For categorical columns, fill with mode.
        Document your approach for each feature with missing data.
 - Scaling Numerical Variables
        Identify all numerical columns (excluding the target variable SalePrice).
        Scale these features using techniques like Min-Max scaling or Standard scaling.
 - Encoding Categorical Variables
        Identify all categorical columns in the dataset.
        Apply appropriate encoding techniques:
            Use One-Hot Encoding for nominal categories.
            Use Label Encoding for ordinal categories, if applicable.
 - Outlier Removal
        Perform an outlier detection analysis on numerical variables (e.g., using the IQR method).
        Remove outliers from these features if they are not representative of typical house prices.
 - Train-Test Split
        Set aside the SalePrice column as the target variable.
        Split the dataset into training (80%) and testing (20%) sets using the train_test_split function from sklearn.

In [9]:
#Data set overview
import pandas as pd
df =pd.read_csv(r"C:\Users\rahul\OneDrive\Desktop\anitha\DSA\dsa assignments\preprocessing assignment\House_Pricing.csv")
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB
None
                 ID    Sale Price  No of Bedrooms  No of Bathrooms  \
count  2.161300e+04  2.160900e+04    21613.000000     21609.000000
mean   4.580302e+09  5.401984e+05        3.370842         2.114732
std    2.876566e+09  3.673890e+05        0.930062         0.770138
min    1.000102e+06  7.500000e+04        0.000000         0.000000
25%    2.123049e+09  3.219500e+05        3.000000         1.750000
50%    3.904930e+09  4.500000e+05        3.000000         2.250000
75%    7.308900e+09  6.450000e+05        4.000000         2.500000
max    9.900000e+09  7.700000e+06       33.000000         8.000000

       Flat Area (in Sqft)  Lot Area (in Sqft)  No of Floors  Overall Grade  \
count         21604.000000        2.160400e+04  21613.000000   21613.000000
mean           2079.931772        1.510776e+04      1.494309       7.623467
std             918.487597        4.142827e+04      0.539989       1.105439
min             290.000000        5.200000e+02      1.000000       1.000000
25%            1429.250000        5.040000e+03      1.000000       7.000000
50%            1910.000000        7.617500e+03      1.500000       7.000000
75%            2550.000000        1.068825e+04      2.000000       8.000000
max           13540.000000        1.651359e+06      3.500000      10.000000

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
count                               21610.000000             21613.000000
mean                                 1788.344193               291.509045
std                                   827.982604               442.575043
min                                   290.000000                 0.000000
25%                                  1190.000000                 0.000000
50%                                  1560.000000                 0.000000
75%                                  2210.000000               560.000000
max                                  9410.000000              4820.000000

       Age of House (in Years)  Renovated Year       Zipcode      Latitude  \
count             21613.000000    21613.000000  21612.000000  21612.000000
mean                 46.994864       84.402258  98077.937766     47.560048
std                  29.373411      401.679240     53.505425      0.138565
min                   3.000000        0.000000  98001.000000     47.155900
25%                  21.000000        0.000000  98033.000000     47.470975
50%                  43.000000        0.000000  98065.000000     47.571800
75%                  67.000000        0.000000  98118.000000     47.678000
max                 118.000000     2015.000000  98199.000000     47.777600

          Longitude  Living Area after Renovation (in Sqft)  \
count  21612.000000                            21612.000000
mean    -122.213892                             1986.538914
std        0.140830                              685.404255
min     -122.519000                              399.000000
25%     -122.328000                             1490.000000
50%     -122.230000                             1840.000000
75%     -122.125000                             2360.000000
max     -121.315000                             6210.000000

       Lot Area after Renovation (in Sqft)
count                         21613.000000
mean                          12768.455652
std                           27304.179631
min                             651.000000
25%                            5100.000000
50%                            7620.000000
75%                           10083.000000
max                          871200.000000

In [10]:
#Duplicate Removal
df=df.drop_duplicates()
df = df.loc[:, ~df.columns.duplicated()]

In [11]:
#identify missing values
print(df.isnull().sum())

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [12]:
# For numerical columns,mean/median imputation.
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].median())
#categorical column with mode
categorical_cols = df.select_dtypes(include=['object']).columns
df[categorical_cols] = df[categorical_cols].apply(lambda x: x.fillna(x.mode()[0]))

In [13]:
#scaling
from sklearn.preprocessing import StandardScaler

# Define features and target
X = df.drop(columns=['Sale Price'])
y = df['Sale Price']

# Identify numerical columns
numerical_cols = X.select_dtypes(include=['float64', 'int64']).columns

# Apply standard scaling
scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

In [14]:
#encoding categorical values
# One-Hot Encoding for nominal(unordered )variables
X = pd.get_dummies(X, drop_first=True)
print(X)
from sklearn.preprocessing import LabelEncoder

             ID  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
0      0.886146       -0.398737        -1.447640            -0.979940
1      0.637511       -0.398737         0.175628             0.533757
2      0.365444       -1.473959        -1.447640            -1.426426
3     -0.727656        0.676485         1.149589            -0.130528
4     -0.912881       -0.398737        -0.149026            -0.435445
...         ...             ...              ...                  ...
21608 -1.500888       -0.398737         0.500282            -0.598793
21609  0.702159        0.676485         0.500282             0.250619
21610 -1.062751       -1.473959        -1.772294            -1.154179
21611 -1.491046       -0.398737         0.500282            -0.522564
21612 -1.062751       -1.473959        -1.772294            -1.154179

       Lot Area (in Sqft)  No of Floors  Overall Grade  \
0               -0.228268     -0.915427      -0.564013
1               -0.189832      0.936506      -0.564013
2               -0.123244     -0.915427      -1.468651
3               -0.243962     -0.915427      -0.564013
4               -0.169600     -0.915427       0.340626
...                   ...           ...            ...
21608           -0.337373      2.788439       0.340626
21609           -0.224333      0.936506       0.340626
21610           -0.332086      0.936506      -0.564013
21611           -0.307025      0.936506       0.340626
21612           -0.338701      0.936506      -0.564013

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
0                                      -0.734756                -0.658681
1                                       0.461025                 0.245141
2                                      -1.229979                -0.658681
3                                      -0.891778                 1.397515
4                                      -0.130826                -0.658681
...                                          ...                      ...
21608                                  -0.312005                -0.658681
21609                                   0.630126                -0.658681
21610                                  -0.928014                -0.658681
21611                                  -0.227455                -0.658681
21612                                  -0.928014                -0.658681

       Age of House (in Years)  ...  Date House was Sold_15 March 2016  \
0                     0.544898  ...                              False
1                     0.681079  ...                              False
2                     1.293892  ...                              False
3                     0.204446  ...                              False
4                    -0.544548  ...                              False
...                        ...  ...                                ...
21608                -1.293542  ...                              False
21609                -1.463768  ...                              False
21610                -1.293542  ...                              False
21611                -1.123316  ...                              False
21612                -1.259497  ...                              False

       Date House was Sold_15 May 2016  Waterfront View_Yes  \
0                                False                False
1                                False                False
2                                False                False
3                                False                False
4                                False                False
...                                ...                  ...
21608                            False                False
21609                            False                False
21610                            False                False
21611                            False                False
21612                            False                False

       No of Times Visited_Once  No of Times Visited_Thrice  \
0                         False                       False
1                         False                       False
2                         False                       False
3                         False                       False
4                         False                       False
...                         ...                         ...
21608                     False                       False
21609                     False                       False
21610                     False                       False
21611                     False                       False
21612                     False                       False

       No of Times Visited_Twice  Condition of the House_Excellent  \
0                           True                             False
1                           True                             False
2                           True                             False
3                           True                              True
4                           True                             False
...                          ...                               ...
21608                       True                             False
21609                       True                             False
21610                       True                             False
21611                       True                             False
21612                       True                             False

       Condition of the House_Fair  Condition of the House_Good  \
0                             True                        False
1                             True                        False
2                             True                        False
3                            False                        False
4                             True                        False
...                            ...                          ...
21608                         True                        False
21609                         True                        False
21610                         True                        False
21611                         True                        False
21612                         True                        False

       Condition of the House_Okay
0                            False
1                            False
2                            False
3                            False
4                            False
...                            ...
21608                        False
21609                        False
21610                        False
21611                        False
21612                        False

[21613 rows x 36 columns]

In [15]:
#outlier removal
#Calculate IQR
Q1 = X[numerical_cols].quantile(0.25)
Q3 = X[numerical_cols].quantile(0.75)
IQR = Q3 - Q1
print("Q1:",Q1,)
print("Q3:",Q3)
print("IQR:",IQR)

# Define outlier condition
outlier_condition = ((X[numerical_cols] < (Q1 - 1.5 * IQR)) | (X[numerical_cols] > (Q3 + 1.5 * IQR)))

# Remove rows with outliers
X = X[~outlier_condition.any(axis=1)]
y = y[X.index]
print(X)
print(y)

Q1: ID                                          -0.854251
No of Bedrooms                              -0.398737
No of Bathrooms                             -0.473679
Flat Area (in Sqft)                         -0.707692
Lot Area (in Sqft)                          -0.242996
No of Floors                                -0.915427
Overall Grade                               -0.564013
Area of the House from Basement (in Sqft)   -0.722678
Basement Area (in Sqft)                     -0.658681
Age of House (in Years)                     -0.885000
Renovated Year                              -0.210128
Zipcode                                     -0.839900
Latitude                                    -0.642675
Longitude                                   -0.810290
Living Area after Renovation (in Sqft)      -0.724470
Lot Area after Renovation (in Sqft)         -0.280859
Name: 0.25, dtype: float64
Q3: ID                                           0.948583
No of Bedrooms                               0.676485
No of Bathrooms                              0.500282
Flat Area (in Sqft)                          0.511977
Lot Area (in Sqft)                          -0.106706
No of Floors                                 0.936506
Overall Grade                                0.340626
Area of the House from Basement (in Sqft)    0.509340
Basement Area (in Sqft)                      0.606670
Age of House (in Years)                      0.681079
Renovated Year                              -0.210128
Zipcode                                      0.748796
Latitude                                     0.851277
Longitude                                    0.631233
Living Area after Renovation (in Sqft)       0.544912
Lot Area after Renovation (in Sqft)         -0.098356
Name: 0.75, dtype: float64
IQR: ID                                           1.802834
No of Bedrooms                               1.075222
No of Bathrooms                              0.973961
Flat Area (in Sqft)                          1.219669
Lot Area (in Sqft)                           0.136290
No of Floors                                 1.851933
Overall Grade                                0.904639
Area of the House from Basement (in Sqft)    1.232017
Basement Area (in Sqft)                      1.265351
Age of House (in Years)                      1.566078
Renovated Year                               0.000000
Zipcode                                      1.588695
Latitude                                     1.493952
Longitude                                    1.441523
Living Area after Renovation (in Sqft)       1.269381
Lot Area after Renovation (in Sqft)          0.182504
dtype: float64
             ID  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
0      0.886146       -0.398737        -1.447640            -0.979940
2      0.365444       -1.473959        -1.447640            -1.426426
3     -0.727656        0.676485         1.149589            -0.130528
4     -0.912881       -0.398737        -0.149026            -0.435445
6     -1.132940       -0.398737         0.175628            -0.397330
...         ...             ...              ...                  ...
21608 -1.500888       -0.398737         0.500282            -0.598793
21609  0.702159        0.676485         0.500282             0.250619
21610 -1.062751       -1.473959        -1.772294            -1.154179
21611 -1.491046       -0.398737         0.500282            -0.522564
21612 -1.062751       -1.473959        -1.772294            -1.154179

       Lot Area (in Sqft)  No of Floors  Overall Grade  \
0               -0.228268     -0.915427      -0.564013
2               -0.123244     -0.915427      -1.468651
3               -0.243962     -0.915427      -0.564013
4               -0.169600     -0.915427       0.340626
6               -0.200045      0.936506      -0.564013
...                   ...           ...            ...
21608           -0.337373      2.788439       0.340626
21609           -0.224333      0.936506       0.340626
21610           -0.332086      0.936506      -0.564013
21611           -0.307025      0.936506       0.340626
21612           -0.338701      0.936506      -0.564013

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
0                                      -0.734756                -0.658681
2                                      -1.229979                -0.658681
3                                      -0.891778                 1.397515
4                                      -0.130826                -0.658681
6                                      -0.088551                -0.658681
...                                          ...                      ...
21608                                  -0.312005                -0.658681
21609                                   0.630126                -0.658681
21610                                  -0.928014                -0.658681
21611                                  -0.227455                -0.658681
21612                                  -0.928014                -0.658681

       Age of House (in Years)  ...  Date House was Sold_15 March 2016  \
0                     0.544898  ...                              False
2                     1.293892  ...                              False
3                     0.204446  ...                              False
4                    -0.544548  ...                              False
6                    -0.816910  ...                              False
...                        ...  ...                                ...
21608                -1.293542  ...                              False
21609                -1.463768  ...                              False
21610                -1.293542  ...                              False
21611                -1.123316  ...                              False
21612                -1.259497  ...                              False

       Date House was Sold_15 May 2016  Waterfront View_Yes  \
0                                False                False
2                                False                False
3                                False                False
4                                False                False
6                                False                False
...                                ...                  ...
21608                            False                False
21609                            False                False
21610                            False                False
21611                            False                False
21612                            False                False

       No of Times Visited_Once  No of Times Visited_Thrice  \
0                         False                       False
2                         False                       False
3                         False                       False
4                         False                       False
6                         False                       False
...                         ...                         ...
21608                     False                       False
21609                     False                       False
21610                     False                       False
21611                     False                       False
21612                     False                       False

       No of Times Visited_Twice  Condition of the House_Excellent  \
0                           True                             False
2                           True                             False
3                           True                              True
4                           True                             False
6                           True                             False
...                          ...                               ...
21608                       True                             False
21609                       True                             False
21610                       True                             False
21611                       True                             False
21612                       True                             False

       Condition of the House_Fair  Condition of the House_Good  \
0                             True                        False
2                             True                        False
3                            False                        False
4                             True                        False
6                             True                        False
...                            ...                          ...
21608                         True                        False
21609                         True                        False
21610                         True                        False
21611                         True                        False
21612                         True                        False

       Condition of the House_Okay
0                            False
2                            False
3                            False
4                            False
6                            False
...                            ...
21608                        False
21609                        False
21610                        False
21611                        False
21612                        False

[16107 rows x 36 columns]
0        221900.0
2        180000.0
3        604000.0
4        510000.0
6        257500.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: Sale Price, Length: 16107, dtype: float64

In [16]:
#Train test split
from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)